bt_joiner:
  name: bt-joiner
  image: linarotechnologies/bt-joiner:latest
  privileged: true
  read_only: true
  restart: always
  network_mode: host
  tmpfs:
    - /var/run
    - /var/lock
    - /var/log
