version: '3'

services:
  bt-joiner:
    image: linarotechnologies/bt-joiner:latest
    privileged: true
    read_only: true
    restart: always
    network_mode: "host"
    tmpfs:
      - /var/run
      - /var/lock
      - /var/log
  cf-proxy-coap-http:
    image: linarotechnologies/cf-proxy-coap-http:latest
    read_only: true
    restart: always
    network_mode: "host"
  nginx-http-proxy:
    image: linarotechnologies/nginx:latest
    command: nginx-debug -g 'daemon off;'
    read_only: true
    restart: always
    network_mode: "host"
    extra_hosts:
      - "gitci.com:192.168.1.26"
    tmpfs:
      - /var/run
      - /var/cache/nginx
    volumes:
      - /tmp/nginx-http-proxy.conf:/etc/nginx/nginx.conf
  nginx-coap-proxy:
    image: image: linarotechnologies/nginx:latest
    command: nginx-debug -g 'daemon off;'
    read_only: true
    restart: always
    network_mode: "host"
    extra_hosts:
      - "gitci.com:192.168.1.26"
    tmpfs:
      - /var/run
    volumes:
      - /tmp/nginx-lwm2m.conf:/etc/nginx/nginx.conf
