version: '3'

services:
  bt-joiner:
    image: linarotechnologies/bt-joiner:latest
    privileged: true
    read_only: true
    restart: always
    network_mode: "host"
    tmpfs:
      - /var/run
      - /var/lock
      - /var/log
  cf-proxy-coap-http:
    image: linarotechnologies/cf-proxy-coap-http:latest
    read_only: true
    restart: always
    network_mode: "host"
