version: '3'

services:
  bt-joiner:
    image: registry.foundries.io/embeddedandroid/gateway-containers/bt-joiner:latest
    privileged: true
    read_only: true
    restart: always
    network_mode: "host"
    tmpfs:
      - /run
      - /var/lock
      - /var/log
  mosquitto:
    image: registry.foundries.io/embeddedandroid/gateway-containers/mosquitto:latest
    read_only: true
    restart: always
    network_mode: "host"
    volumes:
      - /tmp/mosquitto.conf:/etc/mosquitto/conf.d/mosquitto.conf
  nginx-http-proxy:
    image: registry.foundries.io/embeddedandroid/gateway-containers/nginx:latest
    command: nginx-debug -g 'daemon off;'
    read_only: true
    restart: always
    network_mode: "host"
    extra_hosts:
      - "gitci.com:192.168.1.18"
    tmpfs:
      - /var/run
      - /var/cache/nginx
    volumes:
      - /tmp/nginx-http-proxy.conf:/etc/nginx/nginx.conf
