version: '3'

services:
  bt-joiner:
    image: registry.foundries.io/embeddedandroid/gateway-containers/bt-joiner:latest
    privileged: true
    read_only: true
    restart: always
    network_mode: "host"
    tmpfs:
      - /run
      - /var/lock
      - /var/log
  cf-proxy-coap-http:
    image: registry.foundries.io/embeddedandroid/gateway-containers/cf-proxy-coap-http:latest
    read_only: true
    restart: always
    network_mode: "host"
  nginx-coap-proxy:
    image: registry.foundries.io/embeddedandroid/gateway-containers/nginx:latest
    command: nginx-debug -g 'daemon off;'
    read_only: true
    restart: always
    network_mode: "host"
    extra_hosts:
      - "gitci.com:192.168.1.26"
    tmpfs:
      - /var/run
    volumes:
      - /tmp/nginx-lwm2m.conf:/etc/nginx/nginx.conf
